/*Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.*/

#include<iostream>

using namespace std;

int main()
{
	unsigned int m = 1;
	unsigned int n = 2;
	unsigned int sum = 0;
	unsigned int temp;
	const unsigned int MAXNUMBER = 4000000;
	while(n <= MAXNUMBER)
	{
		if(!(n % 2))
			sum += n;
		temp = n;
		n += m;
		m = temp;
	}
	cout<<"SUM: "<<sum<<endl;
	return 0;
}
